### ISSUE TITLE
Installation Error: Dependency Conflict with bladesight on Python 3.12

### ISSUE THREAD

**Issue by MK-SEO82** [Bladesight/bladesight-worksheets#1]
Hello,

I am experiencing an issue while trying to install the bladesight package using pip on Python 3.12. I am currently using Spyder as my IDE. Below are the details of the issue:

**Environment:**
OS: [Windows 11 pro]
Python Version: 3.12
IDE: Spyder (version: [your Spyder version])
pip Version: [pip 24.2 from C:\ProgramData\anaconda3\Lib\site-packages\pip (python 3.12)]

**Issue:**
When running the command pip install bladesight, the installation fails due to dependency conflicts with the install package. The error mentions that bladesight versions depend on install<2.0.0, >=1.3.5. However, pip seems unable to resolve the conflicts across multiple versions.

Here is the error log:

[Include the error log here. For example:]
Collecting bladesight
  ...
The conflict is caused by:
    bladesight 0.12.2 depends on install<2.0.0 and >=1.3.5
    bladesight 0.12.1 depends on install<2.0.0 and >=1.3.5
    ...

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Steps to Reproduce:**
Install Python 3.12.
Open Spyder IDE and activate the Python 3.12 environment.
Run the command pip install bladesight.
**Expected Behavior:**
The package should install without errors.

**Actual Behavior:**
The installation fails due to unresolved dependency conflicts.

**Additional Notes:**
I have already tried updating pip to the latest version and clearing the pip cache, but the issue persists.
The conflict might be related to the compatibility between bladesight and Python 3.12 or the install package.
Could you please help resolve this issue? If additional information or testing is required, I would be happy to assist.

Thank you for your time and support!

Best regards,
MUKYUNG

**Comment by Bladesight** [comment]
Hi MUKYUNG,

Thanks for reporting this. I'll check it out ASAP and get back to you.

In the meanwhile, have you heard of `uv`? Its a new package manager for Python that I've recently started using. I'm definitely going to change the tutorial's installation instructions to `uv` instead of `pip` . 

I highly recommend it.


Here's the process for bladesight:
1. Install uv for your platform (https://docs.astral.sh/uv/getting-started/installation/#installation-methods)
2. Create a new folder and run the following commands in the terminal:
``` console
uv python pin 3.12
uv init
uv add bladesight
```
If you want to use jupyter notebook, run the following as well:
```
uv add jupyter --link-mode copy
```

Your installation should just work!

**Comment by Bladesight** [comment]
Hi @MK-SEO82, 

Bladesight was not yet compatible with Python 3.12, the main reason being that Numba was, until fairly recently, not compatible with 3.12. 

I have now updated Bladesight to version 0.16 to be compatible with Python 3.12.

Will you try again, please?

**Comment by MK-SEO82** [comment]
Hi, @Bladesight 
Thanks to your modifications, the installation worked perfectly on my Python version.
I wish you a happy and healthy end of the year, and may you have a prosperous New Year!

**Comment by Bladesight** [comment]
Awesome, 

I'm glad its resolved MUKYUNG
